### ISSUE TITLE
Autostart auf Home Assistant Green

### ISSUE THREAD

**Issue by MadNasedo** [mmattel/EET-Solmate#20]
Hallo,
ich hab hier HomeAssistant auf einem Home Assistant Green laufen.
Das Script ist installiert und läuft auch wenn ich es vom Terminal aus starte - Daten kommen in MQTT an und ich hab mir auch schon die Werte auf eine Card gelegt.
Aber das die Solmate.py automatisch gestartet wird bekomme ich einfach nicht hin.

Der Befehl:
`sudo systemctl edit --force --full eet.solmate`
ergibt hier nur:
`sudo: systemctl: command not found`

Hatte HomeAssistant vorher auf einem Intel Nuc laufen, aber da wars das gleiche. Leider stehe ich jetzt mit meinen Linux Kentnissen an.

Wie bekomme ich den Autostart noch hin? Hast du da vielleicht eine Idee?
Was ist der Sensor.mppOutI ?

**Comment by mmattel** [comment]
Hier eine Erklärung zu [mpp](https://de.wikipedia.org/wiki/Maximum_Power_Point_Tracking?wprov=sfti1)

Wegen systemd, Du verwendest HASSIO, also ein OS das von HA "downgesized" wurde. Wie ein Autostart in HASSIO bewerkstelligt werden kann weis ich nicht. Da musst schauen, freue mich auf was Du findest. Wenn ich was finde schreib ich.

**Comment by MadNasedo** [comment]
So, alles noch mal von neuem installiert - jetzt läuft gar nichts mehr :(
```
 EET-Solmate git:(main) ✗ python solmate.py
Traceback (most recent call last):
  File "/homeassistant/EET-Solmate/solmate.py", line 7, in <module>
    import schedule
ModuleNotFoundError: No module named 'schedule'
```
Ich denke HASSIO ist zu minimal, um das Script vernünftig zu betreiben.

**Comment by mmattel** [comment]
Sind die Requirements erfüllt? sind alle module vorhanden? Hast du das check-requirements.py script ausgeführt?

**Comment by MadNasedo** [comment]
Ja, die Requirements sind laut Script erfüllt.
` python check_requirements.py
/usr/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

The following modules can be commented in requirements.txt because they are already available:

[]

When done, call: python -m pip install -r requirements.txt

If the call returns an empty array like [], all module requirements are met.
`

**Comment by mmattel** [comment]
Alles der Reihe nach...

KeyError: 'general_add_log'

bedeutet, dass der key in der .env Datei nicht gefunden wurde. Check mal ob in der .env alle keys vom sample drinnen und konfiguriert sind.

**Comment by MadNasedo** [comment]
Die .env war das Problem - ich habe einfach die von der älteren Version gelassen. Alle Werte in die neuere übertragen -> läuft wieder :D 

Jetzt muss ich nur noch rausfinden wie ich den Autostart hinbekomme.

Danke 👍

**Comment by mmattel** [comment]
Sehr gut. Check mal ob in HASSIO systemd vorhanden ist,
zb über https://linuxhandbook.com/check-if-systemd/amp/
bzw gibt es einen folder /etc/system/systemd

**Comment by MadNasedo** [comment]
Hassio benutzt systemd nicht, es wird busybox benützt.
```
➜  ~ stat /sbin/init
  File: '/sbin/init' -> '/bin/busybox'
```

**Comment by BetaTobi** [comment]
#

> Jetzt muss ich nur noch rausfinden wie ich den Autostart hinbekomme.

Bei dem Problem steh ich auch.
Script läuft, aber nach jedem Neustart muss ich einige Python Module neu installieren und das Script auch selbst starten.

Ich such auch nach einer Möglichkeit die nötigen Terminbefehle z.B. via Automation zu senden.
Aber bisher wenig erfolgreich.
Weiß jemand, ob das geht?
Und falls ja, wie?

:-)

**Comment by MadNasedo** [comment]
Same here... sobald in Putty beende oder das Advanced Terminal Addon neustarte, sind auch ein paar Module weg.

**Comment by mmattel** [comment]
Möglicherweise wäre das ein Weg:

https://smarterkram.de/2524/

* Dann bleiben schon einmal die Module da.
* Dann müsste man noch testen ob man mein script damit starten kann.
* Und final müsste man einen schwerwiegenden fehler provozieren um zu sehen ob das Ganze einen selbst getriggerten full script restart überlebt. Dazu könnte man zb einen counter in der Hauptloop in solmate.py einbauen der den reset triggert...

Auch wenn der Betrieb mit RPi und Docker etwas aufwendiger ist, siehe mein anderes Repo, schätze ich die Freiheiten damit sehr!

**Comment by MadNasedo** [comment]
Hab das mal installiert und in die configuration.yaml das reingeschrieben:
```
python_script:
    requirements:
        - asyncio
        - datetime
        - paho-mqtt
        - python-dotenv
        - schedule
        - termcolor
        - websockets   
script:
  solmate:
    sequence:
    - service: python_script.exec
      data_template:  # use `data_template` if you have Jinja2 templates in params
        file: homeassistant/EET-Solmate/solmate.py  # relative path from config folder
        cache: false  # disable cache if you want change python file without reload HA
        title: Solmate Python Script
        time_val: "{{ states('sensor.start_time')|round }}"
```
Aber es werden weder die Module geladen noch das Script gestartet.
